### ISSUE TITLE
failed to enqueue

### ISSUE THREAD

**Issue by ginasuci** [ginasuci/powen-lite-child#2]
![fail1](https://cloud.githubusercontent.com/assets/19280555/16137349/7c77fd40-345c-11e6-8e00-93ebaeddb756.JPG)
pak saya mau pake google font, cari referensi katanya bagusnya di enqueue biar ga load. pertama sempet berhasil, tapi pas tambah font ga ada yg berubah. apa function nya salah ya? @aditiapratama

**Comment by aditiapratama** [comment]
@ginasuci itu register stylenya jangan `googleFonts` semua namanya gin. Namain registernya sesuai dengan nama enqueuenya ya.

**Comment by ginasuci** [comment]
waah makasih banyak pak @aditiapratama
